### ISSUE TITLE
Identity authentication

### ISSUE THREAD

**Issue by linhe0x0** [sqrthree/gold-miner-web#1]

**Comment by actini** [comment]
我把 GitHub 授权和登陆部分做好了，已经 merge 到 develop 分支了，你可以更新查看。稍后你给我一个你的邮箱，我把配置文件发给你 @sqrthree

**Comment by linhe0x0** [comment]
@Romeo0906 目前登录上还存在一个问题，就是登录后返回给前端的是 GitHub 返回的 User 数据，但是缺少了一部分我们站内的数据，需要你这里处理一下，具体的可参考 [d437cf](https://github.com/sqrthree/gold-miner-web-api/commit/d437cf738062fe6a9964dd7abecf1aafd53b63a7)。

**Comment by linhe0x0** [comment]
Looks it's ok.
