### ISSUE TITLE
新译者试译部分功能列表

### ISSUE THREAD

**Issue by linhe0x0** [sqrthree/gold-miner-web#13]
- [x] 新译者进行试译
- [x] 试译文本管理
- [x] 试译申请请求处理
- [x] 消息通知

**Comment by actini** [comment]
此部分都已完成，API 文档也已经更新了，新建了一个推荐文章表 recommend 但由于还需对表结构进行测试，因此推荐表还没写入文档 @sqrthree

**Comment by linhe0x0** [comment]
OK，待调试完就 close 掉。
